pipeline {
    agent any

    environment {
        GRADLE_HOME = tool 'GRADLE_HOME'
        PATH = "$GRADLE_HOME/bin;$PATH" 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Use the globally installed Gradle
                    bat "./gradlew build"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    bat "gradle test"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "test"
                }
            }
        }
    }

    post {
        always {
            echo "test"
        }
    }
}
